# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/warp/catkin_ws/src/rover_base/rover_gps_widget/resource/gps_widget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gps_widget(object):
    def setupUi(self, gps_widget):
        gps_widget.setObjectName("gps_widget")
        gps_widget.resize(938, 647)
        gps_widget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        gps_widget.setAcceptDrops(False)
        self.gridLayout_3 = QtWidgets.QGridLayout(gps_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(gps_widget)
        self.listView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listView.setTabKeyNavigation(True)
        self.listView.setDragEnabled(True)
        self.listView.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listView.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listView.setAlternatingRowColors(True)
        self.listView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 2, 0, 1, 2)
        self.lineEdit_file = QtWidgets.QLineEdit(gps_widget)
        self.lineEdit_file.setInputMask("")
        self.lineEdit_file.setDragEnabled(True)
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.gridLayout.addWidget(self.lineEdit_file, 1, 0, 1, 1)
        self.checkBox_edit = QtWidgets.QCheckBox(gps_widget)
        self.checkBox_edit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_edit.setAutoFillBackground(False)
        self.checkBox_edit.setIconSize(QtCore.QSize(16, 16))
        self.checkBox_edit.setChecked(False)
        self.checkBox_edit.setAutoRepeat(False)
        self.checkBox_edit.setAutoExclusive(False)
        self.checkBox_edit.setTristate(False)
        self.checkBox_edit.setObjectName("checkBox_edit")
        self.gridLayout.addWidget(self.checkBox_edit, 1, 3, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.line_top = QtWidgets.QFrame(gps_widget)
        self.line_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_top.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_top.setObjectName("line_top")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.line_top)
        self.label_currentName = QtWidgets.QLabel(gps_widget)
        self.label_currentName.setObjectName("label_currentName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_currentName)
        self.lineEdit_currentCoord = QtWidgets.QLineEdit(gps_widget)
        self.lineEdit_currentCoord.setReadOnly(True)
        self.lineEdit_currentCoord.setObjectName("lineEdit_currentCoord")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_currentCoord)
        self.label_currentLat = QtWidgets.QLabel(gps_widget)
        self.label_currentLat.setObjectName("label_currentLat")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_currentLat)
        self.doubleSpinBox_currentLat = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_currentLat.setReadOnly(True)
        self.doubleSpinBox_currentLat.setObjectName("doubleSpinBox_currentLat")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_currentLat)
        self.label_currentLong = QtWidgets.QLabel(gps_widget)
        self.label_currentLong.setObjectName("label_currentLong")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_currentLong)
        self.doubleSpinBox_currentLong = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_currentLong.setReadOnly(True)
        self.doubleSpinBox_currentLong.setObjectName("doubleSpinBox_currentLong")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_currentLong)
        self.label_currentDistance = QtWidgets.QLabel(gps_widget)
        self.label_currentDistance.setObjectName("label_currentDistance")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_currentDistance)
        self.doubleSpinBox_currentDistance = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_currentDistance.setReadOnly(True)
        self.doubleSpinBox_currentDistance.setObjectName("doubleSpinBox_currentDistance")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_currentDistance)
        self.label_currentDuration = QtWidgets.QLabel(gps_widget)
        self.label_currentDuration.setObjectName("label_currentDuration")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_currentDuration)
        self.doubleSpinBox_currentDuration = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_currentDuration.setReadOnly(True)
        self.doubleSpinBox_currentDuration.setObjectName("doubleSpinBox_currentDuration")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_currentDuration)
        self.label_currentHeading = QtWidgets.QLabel(gps_widget)
        self.label_currentHeading.setObjectName("label_currentHeading")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_currentHeading)
        self.doubleSpinBox_currentHeading = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_currentHeading.setReadOnly(True)
        self.doubleSpinBox_currentHeading.setObjectName("doubleSpinBox_currentHeading")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_currentHeading)
        self.line_current_preceding = QtWidgets.QFrame(gps_widget)
        self.line_current_preceding.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_current_preceding.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_current_preceding.setObjectName("line_current_preceding")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.line_current_preceding)
        self.label_precedingName = QtWidgets.QLabel(gps_widget)
        self.label_precedingName.setObjectName("label_precedingName")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_precedingName)
        self.lineEdit_precedingCoord = QtWidgets.QLineEdit(gps_widget)
        self.lineEdit_precedingCoord.setReadOnly(True)
        self.lineEdit_precedingCoord.setObjectName("lineEdit_precedingCoord")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_precedingCoord)
        self.label_precedingLat = QtWidgets.QLabel(gps_widget)
        self.label_precedingLat.setObjectName("label_precedingLat")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_precedingLat)
        self.doubleSpinBox_precedingLat = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_precedingLat.setReadOnly(True)
        self.doubleSpinBox_precedingLat.setObjectName("doubleSpinBox_precedingLat")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_precedingLat)
        self.label_precedingLong = QtWidgets.QLabel(gps_widget)
        self.label_precedingLong.setObjectName("label_precedingLong")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_precedingLong)
        self.doubleSpinBox_precedingLong = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_precedingLong.setReadOnly(True)
        self.doubleSpinBox_precedingLong.setObjectName("doubleSpinBox_precedingLong")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_precedingLong)
        self.label_precedingDistance = QtWidgets.QLabel(gps_widget)
        self.label_precedingDistance.setObjectName("label_precedingDistance")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_precedingDistance)
        self.doubleSpinBox_precedingDistance = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_precedingDistance.setReadOnly(True)
        self.doubleSpinBox_precedingDistance.setObjectName("doubleSpinBox_precedingDistance")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_precedingDistance)
        self.label_precedingDuration = QtWidgets.QLabel(gps_widget)
        self.label_precedingDuration.setObjectName("label_precedingDuration")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_precedingDuration)
        self.doubleSpinBox_precedingDuration = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_precedingDuration.setReadOnly(True)
        self.doubleSpinBox_precedingDuration.setObjectName("doubleSpinBox_precedingDuration")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_precedingDuration)
        self.label_precedingHeading = QtWidgets.QLabel(gps_widget)
        self.label_precedingHeading.setObjectName("label_precedingHeading")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_precedingHeading)
        self.line_preceding_next = QtWidgets.QFrame(gps_widget)
        self.line_preceding_next.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_preceding_next.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_preceding_next.setObjectName("line_preceding_next")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.line_preceding_next)
        self.label_nextName = QtWidgets.QLabel(gps_widget)
        self.label_nextName.setObjectName("label_nextName")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_nextName)
        self.lineEdit_nextCoord = QtWidgets.QLineEdit(gps_widget)
        self.lineEdit_nextCoord.setReadOnly(True)
        self.lineEdit_nextCoord.setObjectName("lineEdit_nextCoord")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineEdit_nextCoord)
        self.label_nextLat = QtWidgets.QLabel(gps_widget)
        self.label_nextLat.setObjectName("label_nextLat")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_nextLat)
        self.label_nextLong = QtWidgets.QLabel(gps_widget)
        self.label_nextLong.setObjectName("label_nextLong")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_nextLong)
        self.label_nextDistance = QtWidgets.QLabel(gps_widget)
        self.label_nextDistance.setObjectName("label_nextDistance")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_nextDistance)
        self.label_nextDuration = QtWidgets.QLabel(gps_widget)
        self.label_nextDuration.setObjectName("label_nextDuration")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_nextDuration)
        self.label_nextHeading = QtWidgets.QLabel(gps_widget)
        self.label_nextHeading.setObjectName("label_nextHeading")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.label_nextHeading)
        self.doubleSpinBox_precedingHeading = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_precedingHeading.setReadOnly(True)
        self.doubleSpinBox_precedingHeading.setObjectName("doubleSpinBox_precedingHeading")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_precedingHeading)
        self.doubleSpinBox_nextLat = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_nextLat.setReadOnly(True)
        self.doubleSpinBox_nextLat.setObjectName("doubleSpinBox_nextLat")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_nextLat)
        self.doubleSpinBox_nextLong = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_nextLong.setReadOnly(True)
        self.doubleSpinBox_nextLong.setObjectName("doubleSpinBox_nextLong")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_nextLong)
        self.doubleSpinBox_nextDistance = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_nextDistance.setReadOnly(True)
        self.doubleSpinBox_nextDistance.setObjectName("doubleSpinBox_nextDistance")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_nextDistance)
        self.doubleSpinBox_nextDuration = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_nextDuration.setReadOnly(True)
        self.doubleSpinBox_nextDuration.setObjectName("doubleSpinBox_nextDuration")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_nextDuration)
        self.doubleSpinBox_nextHeading = QtWidgets.QDoubleSpinBox(gps_widget)
        self.doubleSpinBox_nextHeading.setReadOnly(True)
        self.doubleSpinBox_nextHeading.setObjectName("doubleSpinBox_nextHeading")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_nextHeading)
        self.gridLayout.addLayout(self.formLayout, 2, 2, 2, 2)
        self.pushButton_open = QtWidgets.QPushButton(gps_widget)
        self.pushButton_open.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_open.setAcceptDrops(True)
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout.addWidget(self.pushButton_open, 1, 2, 1, 1)
        self.toolButton = QtWidgets.QToolButton(gps_widget)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 1, 1, 1, 1)
        self.gridLayout_bottom = QtWidgets.QGridLayout()
        self.gridLayout_bottom.setObjectName("gridLayout_bottom")
        self.pushButton_start_pause_resume = QtWidgets.QPushButton(gps_widget)
        self.pushButton_start_pause_resume.setAcceptDrops(True)
        self.pushButton_start_pause_resume.setObjectName("pushButton_start_pause_resume")
        self.gridLayout_bottom.addWidget(self.pushButton_start_pause_resume, 0, 0, 1, 1)
        self.pushButton_down = QtWidgets.QPushButton(gps_widget)
        self.pushButton_down.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_down.setObjectName("pushButton_down")
        self.gridLayout_bottom.addWidget(self.pushButton_down, 0, 4, 1, 1)
        self.pushButton_stop = QtWidgets.QPushButton(gps_widget)
        self.pushButton_stop.setEnabled(False)
        self.pushButton_stop.setAcceptDrops(True)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout_bottom.addWidget(self.pushButton_stop, 0, 1, 1, 1)
        self.pushButton_up = QtWidgets.QPushButton(gps_widget)
        self.pushButton_up.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_up.setObjectName("pushButton_up")
        self.gridLayout_bottom.addWidget(self.pushButton_up, 0, 5, 1, 1)
        self.pushButton_goBack = QtWidgets.QPushButton(gps_widget)
        self.pushButton_goBack.setEnabled(False)
        self.pushButton_goBack.setObjectName("pushButton_goBack")
        self.gridLayout_bottom.addWidget(self.pushButton_goBack, 0, 2, 1, 1)
        self.pushButton_manual = QtWidgets.QPushButton(gps_widget)
        self.pushButton_manual.setObjectName("pushButton_manual")
        self.gridLayout_bottom.addWidget(self.pushButton_manual, 0, 3, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(gps_widget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_bottom.addWidget(self.progressBar, 1, 0, 1, 6)
        self.gridLayout.addLayout(self.gridLayout_bottom, 3, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(gps_widget)
        QtCore.QMetaObject.connectSlotsByName(gps_widget)

    def retranslateUi(self, gps_widget):
        _translate = QtCore.QCoreApplication.translate
        gps_widget.setWindowTitle(_translate("gps_widget", "GPS Nav"))
        self.lineEdit_file.setPlaceholderText(_translate("gps_widget", "File path"))
        self.checkBox_edit.setText(_translate("gps_widget", "Edit entry"))
        self.label_currentName.setText(_translate("gps_widget", "Name:"))
        self.label_currentLat.setText(_translate("gps_widget", "Latitude:"))
        self.label_currentLong.setText(_translate("gps_widget", "Longitude:"))
        self.label_currentDistance.setText(_translate("gps_widget", "Distance (m):"))
        self.label_currentDuration.setText(_translate("gps_widget", "Duration (min):"))
        self.label_currentHeading.setText(_translate("gps_widget", "Heading:"))
        self.label_precedingName.setText(_translate("gps_widget", "Preceded by:"))
        self.label_precedingLat.setText(_translate("gps_widget", "Latitude:"))
        self.label_precedingLong.setText(_translate("gps_widget", "Longitude:"))
        self.label_precedingDistance.setText(_translate("gps_widget", "Distance (m):"))
        self.label_precedingDuration.setText(_translate("gps_widget", "Duration (s):"))
        self.label_precedingHeading.setText(_translate("gps_widget", "Heading:"))
        self.label_nextName.setText(_translate("gps_widget", "Followed by:"))
        self.label_nextLat.setText(_translate("gps_widget", "Latitude:"))
        self.label_nextLong.setText(_translate("gps_widget", "Longitude:"))
        self.label_nextDistance.setText(_translate("gps_widget", "Distance (m):"))
        self.label_nextDuration.setText(_translate("gps_widget", "Duration (s):"))
        self.label_nextHeading.setText(_translate("gps_widget", "Heading:"))
        self.pushButton_open.setText(_translate("gps_widget", "Open"))
        self.toolButton.setText(_translate("gps_widget", "..."))
        self.pushButton_start_pause_resume.setText(_translate("gps_widget", "Go"))
        self.pushButton_down.setText(_translate("gps_widget", "▼"))
        self.pushButton_down.setShortcut(_translate("gps_widget", "Alt+Down"))
        self.pushButton_stop.setText(_translate("gps_widget", "Stop"))
        self.pushButton_up.setText(_translate("gps_widget", "▲"))
        self.pushButton_up.setShortcut(_translate("gps_widget", "Alt+Up"))
        self.pushButton_goBack.setText(_translate("gps_widget", "Go back"))
        self.pushButton_manual.setText(_translate("gps_widget", "Manual drive"))

