#!/usr/bin/env python

import sys

from rover_gps_widget import RoverGpsWidgetPlugin
from rqt_gui.main import Main

plugin = 'rover_gps_widget_plugin'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
